const feastDays = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Twenty-First Sunday in Ordinary Time",
    "Saint Augustine, Bishop and Doctor of the Church",
    "The Passion of Saint John the Baptist",
    "Wednesday in the Twenty-First Week in Ordinary Time",
    "Thursday in the Twenty-First Week in Ordinary Time",
    "Friday in the Twenty-First Week in Ordinary Time",
    "Saturday in the Twenty-First Week in Ordinary Time",
    "Twenty-Second Sunday in Ordinary Time",
    "Monday in the Twenty-Second Week in Ordinary Time",
    "Tuesday in the Twenty-Second Week in Ordinary Time",
    "Wednesday in the Twenty-Second Week in Ordinary Time",
    "Thursday in the Twenty-Second Week in Ordinary Time",
    "The Nativity of the Blessed Virgin Mary",
    "Saint Peter Claver, Priest",
    "Twenty-Third Sunday in Ordinary Time",
    "Monday in the Twenty-Third Week in Ordinary Time",
    "Tuesday in the Twenty-Third Week in Ordinary Time",
    "Saint John Chrysostom, Bishop and Doctor",
    "Triumph of the Cross",
    "Our Lady of Sorrows",
    "Saint Cornelius, Pope & Martyr, Saint Cyprian, Bishop & Martyr",
    "Sunday in the Twenty-Fourth Week in Ordinary Time",
    "Monday in the Twenty-Fourth Week in Ordinary Time",
    "Tuesday in the Twenty-Fourth Week in Ordinary Time",
    "Wednesday in the Twenty-Fourth Week in Ordinary Time",
    "Thursday in the Twenty-Fourth Week in Ordinary Time",
    "Friday in the Twenty-Fourth Week in Ordinary Time",
    "Saturday in the Twenty-Fourth Week in Ordinary Time",
    "Sunday in the Twenty-Fifth Week in Ordinary Time",
    "Monday in the Twenty-Fifth Week in Ordinary Time",
    "Tuesday in the Twenty-Fifth Week in Ordinary Time",
    "Wednesday in the Twenty-Fifth Week in Ordinary Time",
    "Thursday in the Twenty-Fifth Week in Ordinary Time",
    "Friday in the Twenty-Fifth Week in Ordinary Time",
    "Saturday in the Twenty-Fifth Week in Ordinary Time",
    "Sunday in the Twenty-Sixth Week in Ordinary Time",
    "Monday in the Twenty-Sixth Week in Ordinary Time",
    "Tuesday in the Twenty-Sixth Week in Ordinary Time",
    "Wednesday in the Twenty-Sixth Week in Ordinary Time",
    "Thursday in the Twenty-Sixth Week in Ordinary Time",
    "Friday in the Twenty-Sixth Week in Ordinary Time",
    "Our Lady of the Rosary",
    "Sunday in the Twenty-Seventh Week in Ordinary Time",
    "Monday in the Twenty-Seventh Week in Ordinary Time",
    "Tuesday in the Twenty-Seventh Week in Ordinary Time",
    "Wednesday in the Twenty-Seventh Week in Ordinary Time",
    "Thursday in the Twenty-Seventh Week in Ordinary Time",
    "Friday in the Twenty-Seventh Week in Ordinary Time",
    "Saturday in the Twenty-Seventh Week in Ordinary Time"
  ];

  export default feastDays;